name: test_techno
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  http_server: '>=0.9.2 <0.10.0'
  json: '>=0.10.0 <0.11.0'
  observe: any
  polymer: '>=0.9.0 <0.10.0'
  polymer_elements: any
  route: '>=0.4.6 <0.5.0'
  sqljocky: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
